language: node_js
node_js:
  - "stable"
install: npm install
services:
  - postgresql
env:
  - NODE_ENV = test
before_script:
  - psql -c 'create database weconnect_test;' -U postgres
  - psql -c "CREATE USERNAME process.env.DB_USERNAME with PASSWORD process.env.DB_PASSWORD;" -U postgres
  - npm run build
  - sequelize db:migrate:undo:all
  - sequelize db:migrate
script: npm test
after_success: npm run coverage