language: node_js
node_js:
  - "stable"
install: npm install
services:
  - postgresql
env:
  - NODE_ENV=test DB_USERNAME=postgres DB_PASSWORD=postgres DB_NAME=weconnect_test
before_script:
  - psql -c 'create database weconnect_test;' -U postgres
  - psql -c "CREATE USER weconnect WITH PASSWORD 'weconnect';" -U postgres
  - npm run build
  - sequelize db:migrate
script: npm test
after_success: npm run coverage