language: node_js
node_js:
  - "stable"
install: npm install
services:
  - postgresql
env:
- NODE_ENV=test DB_USERNAME=postgres DB_PASSWORD=postgres DBNAME=weconnect_test
before_script:
  - psql -c 'create database weconnect_test;' -U postgres
script: npm test
after_success: npm run coverage